################################################################################
# global pipeline config

variables:
  ENV_DIR: ./this-env
  TESTCONF: config/testing.yml
  TESTCONFFULL: config/testing-full.yml
  # speed up cache compression
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: "fast"
  CACHE_COMPRESSION_LEVEL: "fast"
  GIT_SUBMODULE_STRATEGY: recursive

image: condaforge/mambaforge:4.12.0-0

################################################################################
# reusable object to permit lazy coder syndrome

.smk_global_cache: &smk_global_cache
  paths:
    - this-env
  key:
    files:
      - env.yml

.smk_envs_cache: &smk_envs_cache
  paths:
    - .snakemake/conda
  key:
    files:
      - workflow/envs

.smk_resources_cache: &smk_resources_cache
  paths:
    - resources
  key:
    files:
      - config/testing.yml


.activate_smk: &activate_smk
  before_script:
    - eval "$(${CONDA_DIR}/bin/conda shell.bash hook 2> /dev/null)"
    - test -d $ENV_DIR && echo Env exists || mamba env create -f env.yml -p $ENV_DIR
    - conda activate $ENV_DIR

################################################################################
# lint code

run_linters:
  stage: test
  script:
    - echo $CONDA_EXE
    - eval "$(${CONDA_DIR}/bin/conda shell.bash hook 2> /dev/null)"
    - ./setup_dev.sh stratlint
    - ./lint.sh stratlint
  cache:
    paths:
      - stratlint-*
    key:
      files:
        - workflow/scripts/python/*/env.yml
        - workflow/scripts/rmarkdown/*/env.yml

################################################################################
# test snakemake things

snakemake_dry_full:
  stage: test
  <<: *activate_smk
  script:
    - snakemake --use-conda -c 1 --configfile=$TESTCONFFULL all --dryrun
  cache:
    - <<: *smk_global_cache

snakemake_dry:
  stage: test
  <<: *activate_smk
  script:
    - snakemake --use-conda -c 1 --configfile=$TESTCONF all --dryrun
  cache:
    - <<: *smk_global_cache

snakemake_resources:
  stage: test
  <<: *activate_smk
  script:
    - snakemake -p --use-conda -c 8 --configfile=$TESTCONF all_resources
  cache:
    - <<: *smk_global_cache
    - <<: *smk_resources_cache

snakemake_results:
  needs: [snakemake_resources]
  stage: test
  <<: *activate_smk
  script:
    - snakemake -p --use-conda -c 8 --configfile=$TESTCONF all
  cache:
    - <<: *smk_global_cache
    - <<: *smk_envs_cache
    - <<: *smk_resources_cache
